import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00174b",
        "inverse-surface": "#283044",
        background: "#faf8ff",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#eef0ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        secondary: "#3755c3",
        "tertiary-container": "#00788c",
        "surface-dim": "#d2d9f4",
        "on-tertiary-fixed": "#001f26",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        primary: "#004ac6",
        "surface-tint": "#0053db",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#4cd7f6",
        surface: "#faf8ff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c3c6d7",
        "on-primary-container": "#eeefff",
        "on-surface-variant": "#434655",
        tertiary: "#005e6e",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-tertiary-container": "#d7f6ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#173bab",
        "on-secondary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "on-secondary-fixed": "#001453",
        "tertiary-fixed": "#acedff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00217a",
        "secondary-fixed": "#dde1ff",
        "secondary-fixed-dim": "#b8c4ff",
        "secondary-container": "#708cfd",
        "primary-container": "#2563eb",
        "error-container": "#ffdad6",
        outline: "#737686",
        "on-surface": "#131b2e",
        "primary-fixed": "#dbe1ff",
        error: "#ba1a1a",
        "surface-container-low": "#f2f3ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "margin-desktop": "2rem",
        gutter: "1.25rem",
        "margin-tablet": "1.5rem",
        margin: "1rem",
        "space-lg": "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        heading: ["'Plus Jakarta Sans'", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
